# Generated by Django 3.0.2 on 2020-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200205_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_logo',
            field=models.ImageField(default='/images/test1.jpg', upload_to='images/'),
        ),
    ]
