# Generated by Django 3.0.2 on 2020-02-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_logo',
            field=models.ImageField(default='/images/man_2.jpg', upload_to='images/'),
        ),
    ]
